travis:
  secure:
    BINSTAR_TOKEN: KXoJ0hv56p08UKp3SQC+a06UtJtnDLSFZI4+CLbnsWSu6ji4NQMyReJQMbqzriHQe1cwyo9CpCjY+SWQ6PXCxuwrzfF+piwo/iexTuF0HmESFwdtAhIZUR2QppIMnHFc1Bxz59NXi2+ieAC/vSLVfxuab5+cZQ2f41m9Ti6CVGVpAHl5Ia2JnJ7/80TazeTRHaraPzEBw4Ru6Dry1WV5HaLVhXZC7+0at1gj0Va4c8ToN/ISYrhaljm+43p9FDpeyX7x0ypNPDMOaeISn8px3VfUzZbthV7iRXgFeFk5qs+DnavcTguYuynehT7mX/4noOJiI3OI+331s+9W7YaBW+Od+QKwFj2um/m7MZ2Zevq1r/SvoT6zwzcWxSNoPBaUYJSgTCEq0t0sp7y3an8GcvysbrLGooRI/w+KOstFxP/5TYuENE5Z3BIC3ZP9tjW+MEG9SeG6jBdWn8FIWuFFrTRioSB3HoENnzv7QDH5NQ3TpwaMxBPwvq31vbjVqvvXF1yFuMSAjnAlsgEIUJx6bx2wsOLsj/SMefnojAI6b1bfn9k5Qbp17fZyNwQVWa64yzZ+k4c0vKdXyMoEoHY+0is9jwqssr14rEBJKCfwbaIF9oM+7xFNi4A4PUXMTbzf18G/Nlwz8T819EZXMR9h+op1UtMXp3w6H9GUoBum6j8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
